config/urls.py
"""poquito URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
"""

from django.conf import settings
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path

from poquito.views.post import AllPostList, PostCreate, PostDelete, PostDetail, PostList, PostUpdate
from poquito.views.post_card import PostCard
from poquito.views.reaction import ReactionCreate, ReactionDelete
from poquito.views.registration import CheckEmail


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", AllPostList.as_view(), name="home"),
    path("🔑/", include("mailauth.urls")),
    path("🔑/📧🔗/", CheckEmail.as_view(), name="check-email"),
    path("🤔/", PostList.as_view(), name="post-list"),
    path("🤔/🆕/", PostCreate.as_view(), name="post-create"),
    path("🤔/<str:slug>/", PostDetail.as_view(), name="post-detail"),
    path("🤔/<str:slug>/card/", PostCard.as_view(), name="post-card"),
    path("🤔/<str:slug>/✏/", PostUpdate.as_view(), name="post-update"),
    path("🤔/<str:slug>/🗑️/", PostDelete.as_view(), name="post-delete"),
    path("🤔/<str:slug>/😶/🆕/", ReactionCreate.as_view(), name="reaction-create"),
    path("🤔/<str:slug>/😶/<int:pk>/🗑️", ReactionDelete.as_view(), name="reaction-delete"),
]
if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

poquito/models.py
import random
import regex as re

import emoji
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db.models import CASCADE, CharField, DateTimeField, ForeignKey, Model
from django.urls import reverse
from django.utils import timezone

CHARACTERS_PER_LINE = LINES_PER_POST = 8
POST_TOO_LONG_MESSAGE = "🚫 8️⃣✖️8️⃣"


def validate_emoji(text):
    """\u200d is a zero width whitespace"""
    text_without_whitespace = "".join(text.replace("\u200d", "").split())
    invalid_characters = emoji.replace_emoji(text_without_whitespace)
    if invalid_characters:
        message = "🚫 " + ", ".join(sorted(set(invalid_characters)))
        raise ValidationError(message)


def validate_linebreaks(text):
    lines = text.splitlines()
    if len(lines) > LINES_PER_POST:
        raise ValidationError(POST_TOO_LONG_MESSAGE)
    for index, line in enumerate(lines):
        emojis = [grapheme for grapheme in re.findall(r"\X", line) if emoji.is_emoji(grapheme)]
        if len(emojis) > CHARACTERS_PER_LINE:
            raise ValidationError(POST_TOO_LONG_MESSAGE)


class Post(Model):
    class Meta:
        ordering = ("-created_at",)

    text = CharField(max_length=255, validators=[validate_emoji, validate_linebreaks])
    created_at = DateTimeField(editable=False)
    updated_at = DateTimeField(editable=False)
    user = ForeignKey(get_user_model(), on_delete=CASCADE, related_name="posts")
    slug = CharField(default=None, max_length=8, unique=True, validators=[validate_emoji])

    def get_absolute_url(self):
        return reverse("post-detail", args=(self.slug,))

    def save(self, *args, **kwargs):
        self.set_audit_fields()
        self.set_slug()
        super().save(*args, **kwargs)

    def set_audit_fields(self):
        now = timezone.now()
        if not self.id:
            self.created_at = now
        self.updated_at = now

    def set_slug(self):
        if not self.slug:
            all_emoji = list(emoji.EMOJI_DATA.keys())
            self.slug = "".join(random.choice(all_emoji) for _ in range(8))

    @property
    def reaction_summary(self) -> list:
        """
        Construct a list of tuples containing each distinct reaction text with
        it's count. Sort the list in descending order by count.
        """
        summary = dict()
        for reaction in self.reactions.all():
            summary[reaction.text] = summary.setdefault(reaction.text, 0) + 1
        return sorted(summary.items(), key=lambda x: x[1], reverse=True)

    def __str__(self):
        return self.text


class Reaction(Model):
    text = CharField(max_length=4, validators=[validate_emoji])
    created_at = DateTimeField(editable=False)
    updated_at = DateTimeField(editable=False)
    user = ForeignKey(get_user_model(), on_delete=CASCADE, related_name="reactions")
    post = ForeignKey(Post, on_delete=CASCADE, related_name="reactions")

    def get_absolute_url(self):
        return reverse("reaction-detail", args=(self.id,))

    def save(self, *args, **kwargs):
        self.set_audit_fields()
        super().save(*args, **kwargs)

    def set_audit_fields(self):
        now = timezone.now()
        if not self.id:
            self.created_at = now
        self.updated_at = now

    def __str__(self):
        return self.text

poquito/forms.py
from django.forms import ModelForm, Textarea, TextInput

from poquito.models import Post, Reaction


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ("text",)
        widgets = {
            "text": Textarea(
                attrs={
                    "class": "textarea lines",
                    "cols": 8,
                    "rows": 8,
                    "wrap": "hard",
                }
            )
        }


class ReactionForm(ModelForm):
    class Meta:
        model = Reaction
        fields = ("text",)
        widgets = {
            "text": TextInput(
                attrs={
                    "class": "input is-size-7 reaction",
                }
            )
        }

poquito/views/post.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Prefetch
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView

from poquito.models import Post, Reaction
from poquito.forms import PostForm


class CurrentUserFilterMixin:
    """Filter the view's queryset to the currently authed user"""

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AllPostList(ListView):
    model = Post

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            queryset = queryset.prefetch_related(
                Prefetch(
                    "reactions", to_attr="user_reactions", queryset=Reaction.objects.filter(user=self.request.user)
                )
            )
        return queryset.prefetch_related("reactions")


class PostList(CurrentUserFilterMixin, LoginRequiredMixin, ListView):
    model = Post

    def get_queryset(self):
        return super().get_queryset().prefetch_related("reactions")


class PostCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    form_class = PostForm
    model = Post
    success_message = "🆕"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PostDetail(DetailView):
    model = Post

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            queryset = queryset.prefetch_related(
                Prefetch(
                    "reactions", to_attr="user_reactions", queryset=Reaction.objects.filter(user=self.request.user)
                )
            )

        return queryset.prefetch_related("reactions")


class PostUpdate(CurrentUserFilterMixin, LoginRequiredMixin, UpdateView):
    form_class = PostForm
    model = Post


class PostDelete(CurrentUserFilterMixin, LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("post-list")

poquito/views/post_card.py
from poquito.views.post import PostDetail


class PostCard(PostDetail):
    template_name = "poquito/post_card.html"

poquito/views/reaction.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Prefetch
from django.urls import reverse
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.detail import DetailView

from poquito.models import Post, Reaction
from poquito.forms import ReactionForm


class CurrentUserFilterMixin:
    """Filter the view's queryset to the currently authed user"""

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class ReactionCreate(LoginRequiredMixin, CreateView):
    form_class = ReactionForm
    model = Reaction

    def get(self, request, slug):
        self.post = Post.objects.get(slug=slug)
        return super().get(request, slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = self.post
        return context

    def post(self, request, slug):
        self.post = Post.objects.get(slug=slug)
        return super().post(request, slug)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = self.post
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, "🆕")
        return reverse("post-card", args=(self.post.slug,))


class ReactionDelete(CurrentUserFilterMixin, LoginRequiredMixin, DeleteView):
    model = Reaction

    def get(self, request, slug, pk):
        self.post = Post.objects.get(slug=slug)
        return super().get(request, slug, pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = self.post
        return context

    def post(self, request, slug, pk):
        self.post = Post.objects.get(slug=slug)
        return super().post(request, slug, pk)

    def get_success_url(self):
        messages.error(self.request, "🗑️")
        return reverse("post-card", args=(self.post.slug,))

poquito/views/registration.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db import IntegrityError
from django.shortcuts import redirect
from mailauth.views import LoginView as EmailLoginView

EXISTING_USER_MESSAGE = "🤏 📧 🔗 ⏲️ 1️⃣5️⃣"


class CheckEmail(UserPassesTestMixin, EmailLoginView):
    def test_func(self):
        """Only show the signup form to non-authed users"""
        return not self.request.user.is_authenticated

    def handle_no_permission(self):
        """Redirect authed users to the Welcome page"""
        return redirect("post-list")

    def form_valid(self, form):
        """Create the user before sending the login link email"""
        messages.info(self.request, EXISTING_USER_MESSAGE)
        try:
            User = get_user_model()
            User.objects.create_user(form.cleaned_data[User.get_email_field_name()])
        except IntegrityError as exception:
            if "UNIQUE constraint failed" in exception.args[0]:
                messages.info(self.request, EXISTING_USER_MESSAGE)
            else:
                raise
        return super().form_valid(form)

poquito/templates/poquito/index.html
{% extends "poquito/viewport.html" %}

{% block container %}
<div class="tile is-ancestor">
  <div class="tile is-parent is-4">
    <div class="tile is-child">
      <div class="card">
        <div class="card-content">
          <div class="content">
              <h1 class="header has-text-centered is-size-1">🤏️</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="tile is-ancestor">
  {% for object in object_list %}
  {% if forloop.counter0|divisibleby:3 %}
</div>
<div class="tile is-ancestor">
  {% endif %}
  <div class="tile is-parent is-4">
    <div class="tile is-child">
      {% include "poquito/post_card.html" %}
    </div>
  </div>
  {% empty %}
  <div class="tile is-parent">
    <div class="tile is-child card">
      <div class="media-content">
        <div class="content">
          <p>Nothing to see here</p>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

poquito/templates/poquito/post_card.html
<div class="card post-card">
  <div class="card-content p-0">
    <div class="content">
      <div class="lines has-text-centered">{{ post.text|linebreaks }}</div>
      <aside class="is-size-7">
        {% include "poquito/reaction_list.html" with post=post %}
      </aside>
    </div>
  </div>
  <div class="card-footer card-controls">
    {% block controls %}
      <button
        hx-get="{% url 'post-detail' object.slug %}"
        hx-push-url="true"
        hx-select="#viewport"
        hx-swap="outerHTML"
        hx-target="#viewport"
        class="card-footer-item button is-link is-outlined is-small">🔗</button>
      {% if post.user == user %}
          <a href="{% url 'post-update' post.slug %}" class="card-footer-item button is-success is-outlined is-small">✏️</a>
          <a href="{% url 'post-delete' post.slug %}" class="card-footer-item button is-danger is-outlined is-small">🗑️</a>
      {% elif user.is_authenticated %}
          {% if post.user_reactions|first %}
              <button class="card-footer-item button is-danger is-outlined is-small"
                  hx-get="{% url 'reaction-delete' post.slug post.user_reactions.0.id %}"
                  hx-swap="outerHTML"
                  hx-target="closest .post-card"
              >
                  🗑️{{ post.user_reactions|first }}
              </button>
          {% else %}
              <button class="card-footer-item button is-info is-outlined is-small"
                  hx-get="{% url 'reaction-create' post.slug %}"
                  hx-swap="outerHTML"
                  hx-target="closest .post-card"

              >
                  😶
              </button>
          {% endif %}
      {% endif %}
    {% endblock %}
  </div>
</div>

poquito/templates/poquito/post_confirm_delete.html
{% extends "poquito/viewport.html" %}

{% block container %}
<form method="post" hx-boost="true">
  {% csrf_token %}
  <div class="card">
    <div class="card-content p-0">
      <div class="content">
        <div class="lines has-text-centered">{{ object.text|linebreaks }}</div>
      </div>
    </div>
    <div class="card-footer">
      <a href="{% url 'post-detail' object.slug %}" class="card-footer-item button is-link is-outlined is-small">🚫</a>
      <button type="submit" class="card-footer-item button is-danger is-small">🗑️⁉️</button>
    </div>
  </div>
</form>
{% endblock %}

poquito/templates/poquito/post_detail.html
{% extends "poquito/viewport.html" %}

{% block container %}
  {% include "poquito/post_card.html" with post=object%}
{% endblock %}

poquito/templates/poquito/post_form.html
{% extends "poquito/viewport.html" %}

{% block container %}
<form method="post" hx-boost="true">
  {% csrf_token %}
  <div class="card">
    <div class="card-content p-0">
      <div class="content">
        {{ form.non_field_errors }}
        <div class="field">
          <div class="control">
            {{ form.text }}
          </div>
        </div>
      </div>
    </div>
    <div class="card-footer">
      {% if object.slug %}
      <a href="{% url 'post-detail' object.slug %}" class="card-footer-item button is-link is-outlined is-small">🚫</a>
      {% else %}
      <a href="{% url 'post-list' %}" class="card-footer-item button is-link is-outlined is-small">🚫</a>
      {% endif %}
      <button type="submit" class="card-footer-item button is-success is-small">
        💾
      </button>
    </div>
  </div>
</form>
{% if form.text.errors %}
<div class="is-danger">
  {{ form.text.errors }}
</div>
{% endif %}
{% endblock %}

poquito/templates/poquito/post_list.html
{% extends "poquito/viewport.html" %}

{% block container %}
<div class="tile is-ancestor">
  {% for object in object_list %}
  {% if not forloop.first and forloop.counter0|divisibleby:3 %}
</div>
<div class="tile is-ancestor">
  {% endif %}
  <div class="tile is-parent is-4">
    <div class="tile is-child">
      {% include "poquito/post_card.html" with post=object%}
    </div>
  </div>
  {% empty %}
  <div class="tile is-parent">
    <div class="tile is-child card">
      <div class="card-content has-text-centered">
        <a href="{% url 'post-create' %}" class="button is-success is-outlined is-size-1">🆕</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

poquito/templates/poquito/reaction_confirm_delete.html
{% extends "poquito/post_card.html" %}

{% block controls %}
<button type="reset"
  form="unreact"
  class="card-footer-item button is-link is-small"
  hx-get="{% url 'post-card' post.slug %}"
  hx-swap="outerHTML"
  hx-target="closest .post-card"
>
  🚫
</button>
<form id="unreact" class="unreact">
  <button type="submit"
    class="card-footer-item button is-danger is-small"
    hx-post="{% url 'reaction-delete' post.slug object.pk %}"
    hx-swap="outerHTML"
    hx-target="closest .post-card"
  >
    🗑️{{ post.user_reactions|first }}⁉️
  </button>
</form>
{% endblock %}

poquito/templates/poquito/reaction_form.html
{% extends "poquito/post_card.html" %}

{% block controls %}
<button type="reset" form="react"
  class="card-footer-item button is-info is-small"
  hx-get="{% url 'post-card' post.slug %}"
  hx-swap="outerHTML"
  hx-target="closest .post-card"
>
  🚫
</button>
<form id="react" class="react"
  hx-post="{% url 'reaction-create' post.slug %}"
  hx-swap="outerHTML"
  hx-target="closest .post-card"
  hx-trigger="submit"
>
  <input type="text" name="text" required
    {% if form.text.errors %}
      placeholder="{{ form.text.errors|join:', ' }}"
    {% endif %}
    class="card-footer-item input is-small reaction"
    hx-post="{% url 'reaction-create' post.slug %}"
    hx-swap="outerHTML"
    hx-target="closest .post-card"
    hx-trigger="blur changed consume"
  >
</form>
{% endblock %}

poquito/templates/poquito/reaction_list.html
{% for text, count in post.reaction_summary %}
    {{ text }}{{ count }}
{% endfor %}

poquito/templates/poquito/viewport.html
{% extends "layout.html" %}

{% block viewport %}
<div class="container">
  {% block container %}{% endblock %}
</div>
{% endblock %}